config/routes.rb
Rails.application.routes.draw do
  resources :compromissos
  resources :products
  resources :employees
  resources :clients
  resources :events
  resources :calendars
  devise_for :users
  resources :testes
  root 'testes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :cpf, :address, :number_phone, :date_of_birth, :email, :sex, :store, :department, :function, :salary, :admission, :resignation)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-row">
    <div class="form-group col-md-6">
  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </div>
</div>


<div class="form-row">
    <div class="form-group col-md-6">
  <div class="field">
    <%= form.label :number_phone %><br>
    <%= form.text_field :number_phone %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %><br>
    <%= form.date_select :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>
</div>

<div class="form-row">
    <div class="form-group col-md-6">
  <div class="field">
    <%= form.label :sex %><br>
    <%= form.text_field :sex %>
  </div>

  <div class="field">
    <%= form.label :store %><br>
    <%= form.text_field :store %>
  </div>

  <div class="field">
    <%= form.label :department %><br>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :function %><br>
    <%= form.text_field :function %>
  </div>

</div>

<div class="form-row">
    <div class="form-group col-md-6">
  <div class="field">
    <%= form.label :salary %><br>
    <%= form.text_field :salary %>
  </div>

  <div class="field">
    <%= form.label :admission %><br>
    <%= form.date_select :admission %>
  </div>

  <div class="field">
    <%= form.label :resignation %><br>
    <%= form.date_select :resignation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @employee.cpf %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>Number phone:</strong>
  <%= @employee.number_phone %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @employee.date_of_birth %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @employee.sex %>
</p>

<p>
  <strong>Store:</strong>
  <%= @employee.store %>
</p>

<p>
  <strong>Department:</strong>
  <%= @employee.department %>
</p>

<p>
  <strong>Function:</strong>
  <%= @employee.function %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employee.salary %>
</p>

<p>
  <strong>Admission:</strong>
  <%= @employee.admission %>
</p>

<p>
  <strong>Resignation:</strong>
  <%= @employee.resignation %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>