config/routes.rb
Rails.application.routes.draw do
  resources :compromissos
  resources :products
  resources :employees
  resources :clients
  resources :events
  resources :calendars
  devise_for :users
  resources :testes
  root 'testes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teste.rb
class Teste < ApplicationRecord
end

app/controllers/testes_controller.rb
class TestesController < ApplicationController
  before_action :set_testis, only: [:show, :edit, :update, :destroy]

  # GET /testes
  # GET /testes.json
  def index
    @testes = Teste.all
  end

  # GET /testes/1
  # GET /testes/1.json
  def show
  end

  # GET /testes/new
  def new
    @testis = Teste.new
  end

  # GET /testes/1/edit
  def edit
  end

  # POST /testes
  # POST /testes.json
  def create
    @testis = Teste.new(testis_params)

    respond_to do |format|
      if @testis.save
        format.html { redirect_to @testis, notice: 'Teste was successfully created.' }
        format.json { render :show, status: :created, location: @testis }
      else
        format.html { render :new }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testes/1
  # PATCH/PUT /testes/1.json
  def update
    respond_to do |format|
      if @testis.update(testis_params)
        format.html { redirect_to @testis, notice: 'Teste was successfully updated.' }
        format.json { render :show, status: :ok, location: @testis }
      else
        format.html { render :edit }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testes/1
  # DELETE /testes/1.json
  def destroy
    @testis.destroy
    respond_to do |format|
      format.html { redirect_to testes_url, notice: 'Teste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testis
      @testis = Teste.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testis_params
      params.fetch(:testis, {})
    end
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/views/testes/_form.html.erb
<%= form_with(model: testis, local: true) do |form| %>
  <% if testis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testis.errors.count, "error") %> prohibited this testis from being saved:</h2>

      <ul>
      <% testis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/testes/edit.html.erb
<h1>Editing Testis</h1>

<%= render 'form', testis: @testis %>

<%= link_to 'Show', @testis %> |
<%= link_to 'Back', testes_path %>

app/views/testes/new.html.erb
<h1>New Testis</h1>

<%= render 'form', testis: @testis %>

<%= link_to 'Back', testes_path %>

app/views/testes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_testis_path(@testis) %> |
<%= link_to 'Back', testes_path %>